# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=255)),
                ('created_on', models.TimeField(verbose_name=datetime.datetime(2016, 1, 19, 12, 51, 54, 13576, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='student_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradComment.Students'),
        ),
    ]
