# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GradComment', '0003_auto_20160119_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.TimeField(default=datetime.datetime(2016, 1, 19, 14, 4, 12, 586624, tzinfo=utc), verbose_name=datetime.datetime(2016, 1, 19, 14, 4, 12, 586624, tzinfo=utc)),
        ),
    ]
