# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GradComment', '0007_auto_20160119_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.TimeField(default=datetime.datetime(2016, 1, 20, 11, 23, 18, 664622, tzinfo=utc), verbose_name=datetime.datetime(2016, 1, 20, 11, 23, 18, 664603, tzinfo=utc)),
        ),
    ]
