# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GradComment', '0008_auto_20160120_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.TimeField(default=datetime.datetime(2016, 1, 20, 11, 25, 47, 255598, tzinfo=utc), verbose_name=datetime.datetime(2016, 1, 20, 11, 25, 47, 255586, tzinfo=utc)),
        ),
    ]
