# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GradComment', '0009_auto_20160120_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.TimeField(default=datetime.datetime(2016, 1, 20, 11, 34, 37, 927892, tzinfo=utc), verbose_name=datetime.datetime(2016, 1, 20, 11, 34, 37, 927881, tzinfo=utc)),
        ),
    ]
